import { create } from "zustand";

const useSpotStore = create((set) => ({
    spot: null,
    setSpot: (data) => set({ spot: data }),
    openList: null,
    setOpenList: (data) => set({ openList: data }),
    filteredSpot: null,
    setFilteredSpot: (data) => set({ filteredSpot: data }),
    allSpots: null,
    setAllSpots: (data) => set({ allSpots: data }),
    eliminationSpot: null,
    setEliminationSpot: (data) => set({ eliminationSpot: data }),
    pendingSpot: null,
    setPendingSpot: (data) => set({ pendingSpot: data }),
    askPermission: false,
    setAskPermission: (data) => set({ askPermission: data }),
    askPermissionPending: false,
    setAskPermissionPending: (data) => set({ askPermissionPending: data }),
    approveSpotData: null,
    setApproveSpotData: (data) => set({ approveSpotData: data }),
    unApproveSpotData: null,
    setUnApproveSpotData: (data) => set({ unApproveSpotData: data }),
    askPermissionToApprove: false,
    setAskPermissionToApprove: (data) => set({ askPermissionToApprove: data }),
    askPermissionToUnApprove: false,
    setAskPermissionToUnApprove: (data) => set({ askPermissionToUnApprove: data }),
    reset: false,
    setReset: (data) => set({ reset: data }),
    firstRender: 0,
    setFirstRender: (data) => set({ firstRender: data }),
    firstRenderGrid: 0,
    setFirstRenderGrid: (data) => set({ firstRenderGrid: data }),
}));

export default useSpotStore;